### ISSUE TITLE
how to create student, faculty and librarian account?

### ISSUE THREAD

**Issue by jacksolutions** [JayVora-SerpentCS/EduERPv8#2]
How to create student, faculty and librarian accounts in this ERP? if i just assign school student permission and login, it shows lots of errors and it also shows lots of options which student dont need or they should not have access too? any documentation on it?

**Comment by JayVora-SerpentCS** [comment]
Jacksolutions,

We have been working on a document which we can email to you. Kindly share your email.
Other than that, each of the student/librarian/faculties have a separate menu.
Thanks.

**Comment by jacksolutions** [comment]
just sent you an email on your email address 

i have tried every permission, none of them came up with separate menu. can you please guide?

thanks

**Comment by macmaina** [comment]
JayVora-SerpentCS,

I am trying to go through all the modules in EduERPv8. I would appreciate if i would also get a document detailing the different items on the ERP. For example, whats the difference between standards, divisions, mediums and classes? 

Thank you.

**Comment by JayVora-SerpentCS** [comment]
odooems.com has the option now.
We would appreciate to have contribution from your end regarding this.
Thanks.
